version: '3.8'

services:
  postgres_db:
    container_name: tt-postgres_db
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pg_admin:
    container_name: tt-pg-admin4
    image: dpage/pgadmin4
    depends_on:
      - postgres_db
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}

  tt-dev_server:
    container_name: tt-dev-server
    build: 
      context: .
      target: development
    depends_on:
      - postgres_db
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 9000:9000
    environment:
      - NODE_ENV=DEV
    env_file: ./.env
    command: yarn start:dev

volumes:
  postgres-data: